In [15]:
import numpy as np
import cv2
import matplotlib.pyplot as plt
import open3d as o3d
import os

In [18]:
class Camera:
    """
    Camera class for simulating each camera in a stereoscopic setup.
    """
    def __init__(self, width, height, f, coordinate: list, orientation: list):
        self.width = width              # width of the camera sensor in mm
        self.height = height            # height of the camera sensor in mm
        self.f = f                      # focal length of the camera lens
        self.coordinate = coordinate    # coordinate position of the camera [x, y, z]
        self.orientation = orientation  # orientation of the camera [Rx,Ry,Rz] in degrees
        self.matrix = np.array([0,0,0])

    def capture(self):
        "will capture an image of the scene"
        img = np.zeros([self.width, self.height])  # creating blank image placeholder
        return img

    def camera_pyramid(self):
        # this is the pyramid shape that is often used to represent a camera and its pose
        # recommend changing the z-distance to be focal lenght and the x,y to be sensor height and width
        pyramid = np.array([[self.coordinate[0], self.coordinate[1], self.coordinate[2]],
                            [self.coordinate[0]-4,self.coordinate[1]+3,self.coordinate[2] + 10],
                            [self.coordinate[0]+4,self.coordinate[1]+3,self.coordinate[2] + 10],
                            [self.coordinate[0]+4,self.coordinate[1]-3,self.coordinate[2] + 10],
                            [self.coordinate[0]-4,self.coordinate[1]-3,self.coordinate[2] + 10]]
        return pyramid

    self. 

In [17]:
class Object:
    def __init__(self,filename: str, position: list, orientation: list):
        if not isinstance(filename, str):
            raise TypeError("The filename must be a string.")

        self.mesh = o3d.io.read_triangle_mesh(filename)

        # Check if the mesh is loaded correctly
        if not self.mesh.is_empty():
            print("STL file loaded successfully!")
        else:
            print("Failed to load STL file.")

    def visualize(self):
        # Compute vertex normals for better visualization
        self.mesh.compute_vertex_normals()

        # Visualize the 3D mesh
        o3d.visualization.draw_geometries([self.mesh])

    def to_point_cloud(self):
        point_cloud = self.mesh.sample_points_uniformly(number_of_points=10000)  # Adjust the number of points as needed
        return point_cloud

In [4]:
class Laser:
    def __init__(self, position: list, line: bool):
        self.pos = position
        
        if line:
            pass
        else:
            pass

    def project_grid(u, v, theta):
        self.grid_size = no.array([u,v])
        self.cone_angle = theta
        self.dot_diameter = 1 #mm
        

In [12]:
duck_file = os.path.abspath("../../docs/Rubber_Duck.stl")


duck = Object(duck_file, [0,0,500], [0,0,0])
pc = np.asarray(duck.to_point_cloud().points)

print(type(pc))

Lcam = Camera(2560,960, 2.43, [-50,0,0], [0,0,0])
Rcam = Camera(2560,960, 2.43, [50,0,0], [0,0,0])

STL file loaded successfully!
<class 'numpy.ndarray'>


In [13]:
print(pc)

[[ 12.08885101 -30.04470894  65.16532751]
 [ -9.80444415 -28.41194952  41.24189038]
 [-27.61553121 -24.00443845  17.90842196]
 ...
 [ -4.93308091  18.50010874  26.06846538]
 [ 31.60992983  -8.42153883  14.9381101 ]
 [-18.36450211 -27.09885617 -20.63878364]]


In [2]:
help(bool)

Help on class bool in module builtins:

class bool(int)
 |  bool(x) -> bool
 |
 |  Returns True when the argument x is true, False otherwise.
 |  The builtins True and False are the only two instances of the class bool.
 |  The class bool is a subclass of the class int, and cannot be subclassed.
 |
 |  Method resolution order:
 |      bool
 |      int
 |      object
 |
 |  Methods defined here:
 |
 |  __and__(self, value, /)
 |      Return self&value.
 |
 |  __invert__(self, /)
 |      ~self
 |
 |  __or__(self, value, /)
 |      Return self|value.
 |
 |  __rand__(self, value, /)
 |      Return value&self.
 |
 |  __repr__(self, /)
 |      Return repr(self).
 |
 |  __ror__(self, value, /)
 |      Return value|self.
 |
 |  __rxor__(self, value, /)
 |      Return value^self.
 |
 |  __xor__(self, value, /)
 |      Return self^value.
 |
 |  ----------------------------------------------------------------------
 |  Static methods defined here:
 |
 |  __new__(*args, **kwargs)
 |      Create an