In [1]:
import numpy as np
import cv2
import matplotlib.pyplot as plt
import open3d as o3d
import os

Jupyter environment detected. Enabling Open3D WebVisualizer.
[Open3D INFO] WebRTC GUI backend enabled.
[Open3D INFO] WebRTCWindowSystem: HTTP handshake server disabled.


In [2]:
class Camera:
    """
    Camera class for simulating each camera in a stereoscopic setup.
    """
    def __init__(self, width, height, f, coordinate: list, orientation: list):
        self.width = width              # width of the camera sensor in mm
        self.height = height            # height of the camera sensor in mm
        self.f = f                      # focal length of the camera lens
        self.coordinate = coordinate    # coordinate position of the camera [x, y, z]
        self.orientation = orientation  # orientation of the camera [Rx,Ry,Rz] in degrees

    def capture(self):
        "will capture an image of the scene"
        self.img = np.zeros([self.width, self.height])  # creating blank image placeholder
        pass

In [5]:
class Object:
    def __init__(self,filename: str, position: list, orientation: list):
        if not isinstance(filename, str):
            raise TypeError("The filename must be a string.")

        self.mesh = o3d.io.read_triangle_mesh(filename)

        # Check if the mesh is loaded correctly
        if not self.mesh.is_empty():
            print("STL file loaded successfully!")
        else:
            print("Failed to load STL file.")

    def visualize(self):
        # Compute vertex normals for better visualization
        self.mesh.compute_vertex_normals()

        # Visualize the 3D mesh
        o3d.visualization.draw_geometries([self.mesh])

    def to_point_cloud(self):
        point_cloud = self.mesh.sample_points_uniformly(number_of_points=10000)  # Adjust the number of points as needed
        return point_cloud

In [12]:
duck_file = os.path.abspath("../../docs/Rubber_Duck.stl")


duck = Object(duck_file, [0,0,500], [0,0,0])
pc = np.asarray(duck.to_point_cloud().points)

print(type(pc))

Lcam = Camera(2560,960, 2.43, [-50,0,0], [0,0,0])
Rcam = Camera(2560,960, 2.43, [50,0,0], [0,0,0])

STL file loaded successfully!
<class 'numpy.ndarray'>


In [13]:
print(pc)

[[ 12.08885101 -30.04470894  65.16532751]
 [ -9.80444415 -28.41194952  41.24189038]
 [-27.61553121 -24.00443845  17.90842196]
 ...
 [ -4.93308091  18.50010874  26.06846538]
 [ 31.60992983  -8.42153883  14.9381101 ]
 [-18.36450211 -27.09885617 -20.63878364]]
